=== Dhruv-Sadrawala/XML.SEM2.UNIT.2/11.dtd
<!ENTITY % forPersonalInfo "INCLUDE">
<!ENTITY % forResult "IGNORE">

<![%forPersonalInfo;[
	<!ELEMENT personal_info (address,dob)>
	]]>

<![%forResult;[
	<!ELEMENT result (grade)>
	]]>
	
<!ELEMENT address (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT result (#PCDATA)>
<!ELEMENT student (stu_name,personal_info,result)>
<!ELEMENT stu_name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT percentage (#PCDATA)>
<!ELEMENT grade (#PCDATA)>

=== Dhruv-Sadrawala/XML.SEM2.UNIT.2/11.xml
<?xml version="1.0"?>
	<!DOCTYPE student SYSTEM "11.dtd">
	<student>
		<stu_name></stu_name>
		<personal_info>
			<address></address>
			<dob></dob>
			<gender></gender>
			<mobile></mobile>
		</personal_info>
		<result>
			<total></total>
			<percentage></percentage>
			<grade></grade>
		</result>
	</student>
