=== Dhruv-Sadrawala/XML.SEM2.UNIT.2/4.dtd
<!ELEMENT Student (stuName,personal_info,result)>
		<!ELEMENT stuName (#PCDATA)>
		<!ELEMENT personal_info (birthdate,gender,mobile,address)>
		<!ELEMENT address (#PCDATA)>
		<!ELEMENT birthdate (#PCDATA)>
		<!ELEMENT gender (male|female)>
		<!ELEMENT male (#PCDATA)>
		<!ELEMENT female (#PCDATA)>
		<!ELEMENT mobile (#PCDATA)>
		<!ELEMENT result (total,percentage,grade)>
		<!ELEMENT total (#PCDATA)>
		<!ELEMENT percentage (#PCDATA)>
		<!ELEMENT grade (pass|first|distinction|second|fail)>
		<!ELEMENT pass (#PCDATA)>

=== Dhruv-Sadrawala/XML.SEM2.UNIT.2/4 Student.xml
<?xml version ="1.0" encoding="UTF-8"?>
	
	
	<!DOCTYPE Student SYSTEM "4.dtd">
	<Student>
		<stuName>ABC</stuName>
		<personal_info>
			<birthdate>12/03/2004</birthdate>
			<gender>
				<male>YES</male>
			</gender>
			<mobile>0123</mobile>
			<address>sbxnsknx</address>
		</personal_info>
		<result>
			<total>550</total>
			<percentage>60%</percentage>
			<grade>
				<pass>YES</pass>
			</grade>
		</result>
	</Student>
