=== Dhruv-Sadrawala/XML.SEM2.UNIT.2/6.dtd
<!ELEMENT student (name,id,plan)>
		<!ELEMENT name (fname,lname)>
		<!ELEMENT fname (#PCDATA)>
		<!ELEMENT lname (#PCDATA)>
		<!ELEMENT id (#PCDATA)>
		<!ELEMENT plan (courses*)>
		<!ELEMENT courses (course)>
		<!ATTLIST courses year CDATA #REQUIRED>
		<!ELEMENT course (shortName,record*)>
		<!ELEMENT shortName (#PCDATA)>
		<!ELEMENT record (grade,date)>
		<!ELEMENT grade (#PCDATA)>
		<!ELEMENT date (#PCDATA)>

=== Dhruv-Sadrawala/XML.SEM2.UNIT.2/6 Student.xml
<?xml version="1.0"?>
	
	<!DOCTYPE student SYSTEM "6.dtd">
	
	<student>
		<name>
			<fname></fname>
			<lname></lname>
		</name>
		<id></id>
		<plan>
		  <courses year="3">
		     <course>
		        <shortName></shortName>
		        <record>
			      <grade></grade>
			      <date></date>
		        </record>
		     </course>
		   </courses>
		</plan>
	</student>
