=== Dhruv-Sadrawala/XML.SEM2.UNIT.2/7.dtd
<!ELEMENT email (from,to,content)>
		<!ELEMENT from (#PCDATA)>
		<!ELEMENT to (#PCDATA)>
		<!ELEMENT content (#PCDATA | person |exs)*>
		<!ELEMENT co (#PCDATA)>
		<!ELEMENT person (#PCDATA)>
		<!ELEMENT exs (ex+)>
		<!ELEMENT ex (topic,description)>
		<!ELEMENT topic (#PCDATA)>
		<!ELEMENT description (#PCDATA)>

=== Dhruv-Sadrawala/XML.SEM2.UNIT.2/7 Email.xml
<?xml version="1.0"?>
	
	<!DOCTYPE email SYSTEM "7.dtd">
	
	<email>
		<from></from>
		<to></to>
		<content>
			<person></person>
			<exs>
				<ex>
					<topic></topic>
					<description></description>
				</ex>
			</exs>
		</content>
	</email>
